config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('recipes.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from . import views
from django.urls import path
from .views import (
    RecipeListView,
    RecipeCreateView,
    RecipeCategoryListView,
    RecipeUpdateView,
    RecipePublishView,
    RecipeUnpublishView,
)


app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='home'),
    path('baker/<str:username>/', views.baker_profile, name='baker_profile'),
    path('baker/<str:username>/edit/', views.edit_baker_profile,
         name='edit_baker_profile'),
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('recipes/categories/',
         RecipeCategoryListView.as_view(), name='categories'),
    path('recipes/create/', RecipeCreateView.as_view(), name='recipe_create'),
    path('recipes/<slug:slug>/', views.recipe_detail, name='recipe_detail'),
    path(
        'recipes/<slug:slug>/edit/',
        RecipeUpdateView.as_view(),
        name='recipe_edit',
    ),
    path('recipes/<slug:slug>/publish/',
         RecipePublishView.as_view(), name='recipe_publish'),
    path('recipes/<slug:slug>/unpublish/',
         RecipeUnpublishView.as_view(), name='recipe_unpublish'),
    path('recipes/<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('recipes/<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('recipes/<slug:slug>/like/', views.like, name='add_remove_like'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.


class Baker(models.Model):
    class UserTypes(models.TextChoices):
        PROFESSIONAL = 'professional', 'Professional'
        HOME_BAKER = 'home_baker', 'Home Baker'
        BEGINNER = 'beginner', 'Complete Beginner'
        HOPELESS = 'hopeless', 'Hopeless Baker'
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = CloudinaryField('image', default='placeholder')
    user_type = models.CharField(
        max_length=50, choices=UserTypes.choices, default=UserTypes.BEGINNER)

    def __str__(self):
        return f"Baker {self.user.username}"


class Recipe(models.Model):
    title = models.CharField(max_length=100)
    baker = models.ForeignKey(Baker, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True,)
    image = CloudinaryField('image', default='placeholder')
    ingredients = models.TextField()
    instructions = models.TextField()
    time_required = models.CharField(max_length=50)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    categories = models.ManyToManyField('Category', related_name='tags')
    excerpt = models.TextField(default='', verbose_name='blurb')

    def __str__(self):
        return f"{self.title} by {self.baker.user.username}"

    class Meta:
        ordering = ['-created_on']


class Category(models.Model):
    class TagTypes(models.TextChoices):
        DIETARY = 'dietary', 'Dietary'
        ALLERGY = 'allergy', 'Allergy'
        CUISINE = 'cuisine', 'Cuisine'
    tag_name = models.CharField(max_length=50, unique=True)
    # recipes = models.ManyToManyField(Recipe, blank=True)
    tag_type = models.CharField(max_length=50, choices=TagTypes.choices)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['tag_name']

    def __str__(self):
        return self.tag_name


class Comment(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='comments')
    baker = models.ForeignKey(
        Baker, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.comment} by {self.baker.user.username}"

    class Meta:
        ordering = ['created_on']


class Like(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='likes')
    baker = models.ForeignKey(Baker, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Baker {self.baker.user.username} liked {self.recipe.title}"

    class Meta:
        ordering = ['created_on']

recipes/forms.py
from .models import Recipe, Comment, Baker
from django import forms
from django_summernote.widgets import SummernoteWidget
from cloudinary.forms import CloudinaryFileField


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'image', 'ingredients', 'instructions',
                  'time_required', 'categories', 'excerpt']
        widgets = {
            'ingredients': SummernoteWidget(),
            'instructions': SummernoteWidget(),
            'image': CloudinaryFileField().widget,
        }
        labels = {
            'title': 'Title (Your Recipe Name)',
            'image': 'Image (Make it look delicious)',
            'ingredients': 'Ingredients (Be specific!)',
            'instructions': 'Instructions (Be detailed, use numbered steps)',
            'time_required': 'Time Required (e.g. 30 minutes)',
            'categories': 'Categories (Select all that apply)',
            'excerpt': 'Blurb (Short description of your recipe)',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {
            'comment': 'Comment',
        }
        help_texts = {
            'comment': 'Leave a comment',
        }


class LikeForm(forms.Form):
    pass


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Baker
        fields = ['bio', 'profile_pic', 'user_type']
        widgets = {
            'bio': SummernoteWidget(),
            'profile_pic': CloudinaryFileField().widget,
        }
        labels = {
            'bio': 'Biography (A little about yourself)',
            'profile_pic': 'Profile Picture',
            'user_type': 'User Type',
        }

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic, View

# from django.views.generic.edit import *
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import redirect
from django.db import models
from django.db.models import Prefetch
from .models import Recipe, Comment, Like, Category, Baker
from .forms import RecipeForm, CommentForm, ProfileForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.


class RecipeListView(generic.ListView):
    template_name = 'recipes/recipe_list.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = Recipe.objects.filter(is_published=True).annotate(
            comment_count=models.Count('comments', filter=models.Q(
                comments__approved=True))).order_by(
                    '-created_on')
        return queryset


class RecipeCreateView(generic.CreateView):
    model = Recipe
    template_name = 'recipes/recipe_form.html'
    form_class = RecipeForm

    def form_valid(self, form):
        form.instance.baker = self.request.user.baker
        form.instance.slug = slugify(form.instance.title)
        # Add a message saying that the recipe has been submitted for approval
        messages.add_message(
            self.request, messages.SUCCESS,
            f"{form.instance.title} Recipe submitted and awaiting approval"
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'recipes:recipe_detail',
            kwargs={"slug": self.object.slug}
        )


class RecipeUpdateView(
    LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView
):
    model = Recipe
    template_name = 'recipes/recipe_form.html'
    form_class = RecipeForm

    def test_func(self):
        return (
            self.request.user.is_superuser or
            self.request.user.baker == self.get_object().baker
        )

    def handle_no_permission(self):
        messages.error(
            self.request, "You do not have permission to edit this recipe"
        )
        return redirect("recipes:recipe_detail", slug=self.get_object().slug)

    def form_valid(self, form):
        form.instance.is_published = False
        # Add a message saying that the recipe has been updated
        # and is awaiting approval
        messages.add_message(
            self.request, messages.SUCCESS,
            f"{self.object.title} Recipe updated and awaiting approval"
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'recipes:recipe_detail',
            kwargs={"slug": self.object.slug}
        )

# superuser publish view to publish recipes


class RecipePublishView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self, slug):
        recipe = get_object_or_404(Recipe, slug=slug)
        messages.error(
            self.request,
            "You do not have permission to publish this recipe"
        )
        return redirect("recipes:recipe_detail", slug=recipe.slug)

    def post(self, request, slug):
        recipe = get_object_or_404(Recipe, slug=slug)
        recipe.is_published = True
        recipe.save()
        messages.success(request, "Recipe published")
        return redirect("recipes:recipe_detail", slug=recipe.slug)


# psuedo delete view to unpublish recipes
class RecipeUnpublishView(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return (
            self.request.user.is_superuser or
            self.request.user.baker == self.get_object().baker
        )

    def handle_no_permission(self, slug):
        recipe = get_object_or_404(Recipe, slug=slug)
        messages.error(
            self.request,
            "You do not have permission to unpublish this recipe"
        )
        return redirect("recipes:recipe_detail", slug=recipe.slug)

    def post(self, request, slug):
        recipe = get_object_or_404(Recipe, slug=slug)
        recipe.is_published = False
        recipe.save()
        messages.success(request, "Recipe unpublished")
        return redirect("recipes:recipe_detail", slug=recipe.slug)


def recipe_detail(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    comment_count = recipe.comments.all().count()
    # if not request.user.is_superuser and request.user.baker != recipe.baker
    # and not recipe.is_published:
    if not (
        recipe.is_published or
        request.user.is_authenticated and (
            request.user.is_superuser or
            request.user.baker == recipe.baker
        )
    ):
        messages.error(request, "This recipe is not published yet.")
        return redirect("recipes:recipes")

    liked_bakers = [like.baker for like in recipe.likes.all()]
    if request.user.is_superuser:
        comments = recipe.comments.all().order_by("-created_on")
    else:
        comments = recipe.comments.filter(
            approved=True
        ).order_by("-created_on")
    comment_count = recipe.comments.filter(approved=True).count()
    comment_form = CommentForm()

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.baker = request.user.baker
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                "Comment submitted and awaiting approval"
            )
            return redirect("recipes:recipe_detail", slug=slug)

    return render(
        request,
        "recipes/recipe_detail.html",
        {
            "recipe": recipe,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
            "liked_bakers": liked_bakers,
        },
    )


@login_required
def like(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug)
    if request.method == "POST":

        # Use get_or_create which returns a tuple containing object and bool
        # (the bool specified whether something was creatd by this request)
        like, created = Like.objects.get_or_create(
            recipe=recipe,
            baker=request.user.baker,
        )
        if created:
            messages.success(request, "You have liked this recipe!")
        if not created:
            like.delete()
            messages.success(request,
                             "You have removed your like from this recipe!")
        return redirect("recipes:recipe_detail", slug=slug)
    else:
        return HttpResponseBadRequest("Invalid request method.")


def comment_edit(request, slug, comment_id):
    #  view to edit comments
    queryset = Recipe.objects.filter(is_published=1)
    recipe = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and (
            comment.baker == request.user.baker or request.user.is_superuser
        ):
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.approved = False
            comment.save()
            messages.success(request, "Comment Updated!")
            return HttpResponseRedirect(reverse("recipes:recipe_detail",
                                                args=[slug]))
        else:
            messages.error(request,
                           "Error updating comment. Please check your input.")
            return render(
                request,
                "recipes/recipe_detail.html",
                {
                    "comment_form": comment_form,
                    "recipe": recipe,
                    "comment": comment,
                },
            )

    else:  # Handle GET request implicity (maybe make this explicit?)
        comment_form = CommentForm(instance=comment)
        return render(
            request,
            "recipes/recipe_detail.html",
            {
                "comment_form": comment_form,
                "recipe": recipe,
                "comment": comment,
                "edit_mode": True,
            },
        )


def comment_delete(request, slug, comment_id):
    """
    View to delete a comment associated with a recipe.

    Args:
        request: The HTTP request object.
        slug: The slug of the recipe.
        comment_id: The ID of the comment to be deleted.

    Returns:
        HttpResponseRedirect: Redirects to the recipe detail page.
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if comment.baker == request.user.baker or request.user.is_superuser:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, "Comment Deleted!")
    else:
        messages.add_message(request, messages.ERROR,
                             "Error deleting comment!")
    return HttpResponseRedirect(reverse("recipes:recipe_detail", args=[slug]))


def index(request):
    return render(request, 'recipes/index.html')


class RecipeCategoryListView(generic.ListView):
    model = Recipe
    template_name = 'recipes/recipe_categories.html'
    # create a view that lists all the categories
    # and the recipes in each category as links

    def get_queryset(self):
        return Category.objects.prefetch_related(
            Prefetch('tags', queryset=Recipe.objects.filter(is_published=True))
        )

# View to see the baker profile page


def baker_profile(request, username):
    baker = get_object_or_404(Baker, user__username=username)

recipes/templates/recipes/baker_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- page to view baker profile photo, name, bio, recipes and user type -->
<div class="container mt-4">
    <div class="row g-0 profile-page">
        <div class="col-12 text-center mb-3">
            <h2>Baker {{ baker.user.username }}</h2>
            {% if request.user == baker.user %}
        <a role="button" class="btn btn-primary" href="{% url 'recipes:edit_baker_profile' username=baker.user.username %}">Edit Profile</a>
        {% endif %}
        </div>
        <div class="col-4 baker-pic">
            <img src="{{ baker.profile_pic.url }}" class="img-fluid baker-pic" alt="{{ baker.user.username }}">
        </div>
        <div class="col-12 col-md-7 baker-bio mt-3">
            <h3>A bit about Baker {{ baker.user.username }}</h3>
        <p>{{ baker.bio }}</p>
            <p>I would call myself a {{ baker.get_user_type_display }}</p>
        </div>
        <div class="col-12 mt-3 recipe-list">
            <h3>Recipes by Baker {{ baker.user.username }}</h3>
            <ul>
                {% for recipe in recipes %}
                <li><a href="{% url 'recipes:recipe_detail' recipe.slug %}">{{ recipe.title }}</a></li>
                {% empty %}
                <li>No recipes available by this baker.</li>
                {% endfor %}
            </ul>
        </div>
        
    </div>



{% endblock %}

recipes/templates/recipes/profile_form.html
{% extends "base.html" %}


{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2>Edit your profile</h2>
            <p>Tell other bakers more about yourself and add a profile picture</p>
            <p>Fill in the form below to edit your profile</p>
            <div class="recipe-form mt-4">
                
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Update Profile">
                </form>
                
          
            </div>
        </div>
    </div>
</div>

{% endblock %}

recipes/templates/recipes/recipe_categories.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Recipe Categories</h1>
            <p class="lead">Browse our collection of recipes by category.</p>
        </div>
    {% for category in object_list %}
    <div class="category">
        <h3>{{ category.tag_name }}</h3>
        <ul>
            {% for recipe in category.tags.all %}
            <li><a href="{% url 'recipes:recipe_detail' recipe.slug %}">{{ recipe.title }}</a></li>
            {% empty %}
            <li>No recipes available in this category.</li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
</div>





{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="masthead">
  <div class="container text-center">
    <div class="row g-0 align-items-center">
      <div class="col-6 masthead-text">
        <!-- Post title goes in these h1 tags -->
        <h1 class="post-title">{{ recipe.title }}</h1>
        {% if request.user.is_superuser or recipe.baker == request.user.baker %}
        <a role="button" href="{% url 'recipes:recipe_edit' slug=recipe.slug %}" class="btn btn-primary">Edit Recipe</a>
        {% if recipe.is_published %}
        <form method="POST" action="{% url 'recipes:recipe_unpublish' slug=recipe.slug %}">
          {% csrf_token %}
          <button id="unpublish-button" type="submit" class="btn btn-danger">Unpublish Recipe</button>
        </form>
        {% else %}
        <button class="btn btn-danger" disabled>Unpublished</button>
        {% endif %}
        {% if request.user.is_superuser and not recipe.is_published %}
        <form method="POST" action="{% url 'recipes:recipe_publish' slug=recipe.slug %}">
          {% csrf_token %}
          <button id="publish-button" type="submit" class="btn btn-success">Publish Recipe</button>
        </form>
        {% endif %}

        {% endif %}
        <!-- Post author goes before the | the post's created date goes after -->
        <p class="post-subtitle"><a href="{% url 'recipes:baker_profile'  recipe.baker.user %}">{{ recipe.baker }}</a> |
          {{ recipe.created_on }}</p>
        <p class="post-subtitle"><a href="{% url 'recipes:categories' %}">Categories</a>:
          {% for category in recipe.categories.all %}
          {{ category.tag_name }}{% if not forloop.last %}, {% endif %}
          {% empty %}
          No categories assigned.
          {% endfor %}
        </p>
      </div>
      <div class="col-6 text-center">
        <img src="{{ recipe.image.url }}" class="recipe-image-main" id="recipe-image-main" alt="{{ recipe.title }}">
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12 card mb-4 mt-3">
      <div class="card-body">
        <h2>Ingredients List</h2>
        <!-- The ingredients content goes inside the card-text. -->
        <!-- Use the | safe filter inside the template tags -->
        <p class="card-text">
          {{ recipe.ingredients | safe }}
        </p>
      </div>
    </div>
    <div class="col-12 card mb-4 mt-3">
      <div class="card-body">
        <h2>Instructions</h2>
        <!-- The instructions content goes inside the card-text. -->
        <!-- Use the | safe filter inside the template tags -->
        <p class="card-text">
          {{ recipe.instructions | safe }}
        </p>
      </div>
    </div>
  </div>
  <!-- Displaying count of comments -->
  <div class="row">
    <div class="col-12">
      <strong class="text-secondary">
        <i class="far fa-comments"></i> {{ comment_count }}
        <i class="far fa-thumbs-up"></i> {{ recipe.likes.count }}
      </strong>
    </div>
    <div class="col-12">
      <hr>
    </div>
    <form method="POST" action="{% url 'recipes:add_remove_like' slug=recipe.slug %}">
      {% csrf_token %}
      <button id="likeButton" type="submit" class="btn btn-primary">
        {% if request.user.baker in liked_bakers %}
        Remove Like for this recipe
        <i class="far fa-icon-remove"></i>
        {% else %}
        Like this recipe
        <i class="far fa-thumbs-up"></i>
        {% endif %}
      </button>
    </form>

  </div>
  <!-- Displaying Comments -->
  <div class="row" id="comments">
    <div class="col-md-8 card mb-4  mt-3 ">
      <h3>Comments:</h3>
      <div class="card-body">
        <!-- We want a for loop inside the empty control tags
          to iterate through each comment in comments -->
        {% for comment in comments %}
        <div class="p-2 comments
        {% if not comment.approved and request.user.is_superuser or comment.baker == request.user.baker %}
        text-muted{% elif not comment.approved and not request.user.is_superuser %} d-none{% endif %}">
          <p class="fw-bold">
            {{ comment.baker }}
            <span class="fw-normal">
              {{ comment.created_on }}
            </span> wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.comment | linebreaks }}
          </div>
          <p class="approval">
            {% if comment.baker == request.user.baker %}
            This comment is awaiting approval
            {% elif request.user.is_superuser %}
            This comment is awaiting approval (visible to superusers)
            {% endif %}
          </p>
          {% if user.is_authenticated and comment.baker == request.user.baker %}
          <a role="button" href="{% url 'recipes:comment_edit' slug=recipe.slug comment_id=comment.id %}#comments"
            class="btn btn-edit btn-sm btn-warning" data-comment-id="{{ comment.id }}">Edit</a>
          <button type="button" class="btn btn-delete btn-sm btn-danger" data-comment-id="{{ comment.id }}">Delete</button>
            {% endif %}
        </div>
        {% endfor %}
        <!-- Our for loop ends here -->
      </div>
    </div>
    <!-- Creating New Comments -->
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Leave a comment:</h3>
        <p>Posting as: {{ request.user.baker }}</p>
        <form id="commentForm" method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
          {% if edit_mode %}
          <a href="{% url 'recipes:recipe_detail' slug=recipe.slug %}#comments"
            class="btn btn-secondary btn-lg">Cancel</a>
          {% endif %}
        </form>
        {% else %}
        <p><a href="{% url 'account_login' %}">Log in</a> to leave a comment</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'assets/js/comments.js' %}"></script>
{% endblock %}

recipes/templates/recipes/recipe_form.html
{% extends "base.html" %}


{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2>Add a New Recipe</h2>
            <p>Share your favourite recipes with friends</p>
            <p>Fill in the form below to add a new recipe</p>

            <div class="recipe-form mt-4">
                {% if user.is_authenticated %}
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Submit Recipe">
                </form>
                {% else %}
          <p><a href="{% url 'account_login' %}">Log in</a> to create a recipe</p>
          {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="container mt-4">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">All Recipes</h1>
        </div>
    <div class="row">
        {% for recipe in object_list %}
        <div class="col-md-6 col-xl-4 mb-4 d-flex align-items-stretch">
            <div class="card ">
                <img src="{{ recipe.image.url }}" class="card-img-top recipe-image" alt="{{ recipe.title }}">
                <div class="card-body recipe-card">
                    <h5 class="card-title text-center">{{ recipe.title }}</h5>
                    <!-- <h6 class="card-subtitle mb-2 text-muted">By {{ recipe.baker }}</h6> -->
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item card-subtitle mb-2 text-muted">By <a href="{% url 'recipes:baker_profile'  recipe.baker.user %}">{{ recipe.baker }}</a></li>
                        <li class="list-group-item">Time required: {{ recipe.time_required | safe }}</li>
                        <li class="list-group-item recipe-excerpt">{{ recipe.excerpt | safe }}</li>
                      
                      <li class="list-group-item">
                      
                      <p class="text-center mt-3">Number of comments: <i class="far fa-comments"></i> {{ recipe.comment_count }}</p> 
                      <p class="text-center">Number of likes: <i class="far fa-thumbs-up"></i> {{ recipe.likes.count }}</p></li>
                      </ul>
                      <a href="{% url 'recipes:recipe_detail' recipe.slug %}" class="recipe-link btn btn-secondary">View Recipe</a>
                
            </div>
                <div class="card-footer">
                    <small class="text-muted">Posted on {{ recipe.created_on }}</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock %}