config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('recipes.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from . import views
from django.urls import path
from .views import (
    RecipeListView,
    RecipeCreateView,
    RecipeCategoryListView,
    RecipeUpdateView,
    RecipePublishView,
    RecipeUnpublishView,
)


app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='home'),
    path('baker/<str:username>/', views.baker_profile, name='baker_profile'),
    path('baker/<str:username>/edit/', views.edit_baker_profile,
         name='edit_baker_profile'),
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('recipes/categories/',
         RecipeCategoryListView.as_view(), name='categories'),
    path('recipes/create/', RecipeCreateView.as_view(), name='recipe_create'),
    path('recipes/<slug:slug>/', views.recipe_detail, name='recipe_detail'),
    path(
        'recipes/<slug:slug>/edit/',
        RecipeUpdateView.as_view(),
        name='recipe_edit',
    ),
    path('recipes/<slug:slug>/publish/',
         RecipePublishView.as_view(), name='recipe_publish'),
    path('recipes/<slug:slug>/unpublish/',
         RecipeUnpublishView.as_view(), name='recipe_unpublish'),
    path('recipes/<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('recipes/<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('recipes/<slug:slug>/like/', views.like, name='add_remove_like'),
]

templates/base.html
{% url 'home' as home_url %}
{% load static %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Bakes Between Friends</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A community website to share and explore baking recipes.">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- bootstrap 5 css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static '/assets/css/style.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/assets/images/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/assets/images/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/assets/images/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static '/assets/images/favicons/site.webmanifest' %}">
</head>

<body class="d-flex flex-column main-bg min-vh-100">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light nav sticky-top" aria-label="Main Navigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'recipes:home' %}"><img src="{% static '/assets/images/logo.png' %}"
                    alt="Bakes Between Friends logo" class="logo">
                <span class="brand d-none d-sm-inline">Bakes Between Friends</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page"
                            href="{% url 'recipes:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes:recipes' %}">Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes:categories' %}">Recipe Categories</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes:recipe_create' %}">Share Recipe</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes:baker_profile'  username=request.user.username %}">View Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="text-muted">
                    {% if user.is_authenticated %}
        Logged in as {{ user.baker }}
        {% else %}
        You are not logged in
        {% endif %}
                </span>
            </div>
        </div>
    </nav>
    <!-- displaying Django messages only if a message is present -->
     {% if messages %}
    <div class="container p-0">
        <div class="row">
            <div class="col-12">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-info alert-dismissible
          fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Log in confirmation -->
    <main class="flex-shrink-0 main-bg" id="main-content">
        

        <!-- Main Content -->
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

    </main>


    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-dark text-light text-center">
        <p class="m-0">Made by Bakes Between Friends Team</p>
        <p class="m-0">Follow us:
            <a href="https://www.facebook.com/" target="_blank" rel="noopener"
                aria-label="Visit our Facebook page (opens in a new tab)">
                <i class="fa-brands fa-facebook ms-3"></i></a>
            <a href="https://www.X.com/" target="_blank" rel="noopener"
                aria-label="Visit our X (formerally Twitter) page (opens in a new tab)">
                <i class="fa-brands fa-x-twitter ms-3"></i></a>
            <a href="https://www.instagram.com/" target="_blank" rel="noopener"
                aria-label="Visit our Instagram page (opens in a new tab)">
                <i class="fa-brands fa-instagram-square ms-3"></i></a>
            <a href="https://www.youtube.com/" target="_blank" rel="noopener"
                aria-label="Visit our YouTube page (opens in a new tab)">
                <i class="fa-brands fa-youtube-square ms-3"></i></a>
        </p>
        <p class="m-0">Copyright 2025</p>
    </footer>


    <!-- font awesome 6 -->
    <script src="https://kit.fontawesome.com/f9685659b9.js" crossorigin="anonymous"></script>
    <!-- bootstrap 5 js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
        </script>

    {% block extras %}
    {% endblock %}
</body>

</html>